name: build-native

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download apt packages
      run: |
        sudo apt update
        sudo apt install -y make cmake ninja-build\
            g++\
            g++-aarch64-linux-gnu\
            g++-mingw-w64-x86-64

    - name: Checkout current commit
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: false
    - name: Pull submodules
      run: git submodule update --init --recursive --depth 1

    - name: Set variables
      id: vars
      shell: bash
      run: |
        echo "git-submodule-sha=$(git submodule status ggwave | awk '{print $1}' | sed 's/[^0-9a-f]//g')" >> "$GITHUB_OUTPUT"
        echo "runtimes-dir=${{ github.workspace }}/src/ggwave.net/runtimes" >> "$GITHUB_OUTPUT"
     
    - name: Build
      run: make linux linux-cross-win

    - name: Show build results
      run: tree ${{ steps.vars.outputs.runtimes-dir }}
    
    - name: Upload native build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: natives-all-${{ steps.vars.outputs.git-submodule-sha }}
        path: |
          ${{ steps.vars.outputs.runtimes-dir }}
