# Build ggwave.net nuget package
name: build-nupkg

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  call-build-submodule:
    uses: ./.github/workflows/build-submodule.yml

  build:
    needs: [ call-build-submodule ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current commit
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: false
    
    - name: Set variables
      id: vars
      shell: bash
      run: |
        echo "git-submodule-sha=$(git submodule status ggwave | awk '{print $1}' | sed 's/[^0-9a-f]//g')" >> "$GITHUB_OUTPUT"
        echo "runtimes-dir=${{ github.workspace }}/src/ggwave.net/runtimes" >> "$GITHUB_OUTPUT"
    
    - name: Download native libraries
      env:
        ACTIONS_STEP_DEBUG: true
      uses: dawidd6/action-download-artifact@v9
      with:
        name: natives-all-${{ steps.vars.outputs.git-submodule-sha }}
        path: ${{ steps.vars.outputs.runtimes-dir }}
        branch: ${{ github.head_ref || github.ref_name }}
        search_artifacts: true
        workflow_search: true
        workflow_conclusion: ""
    
    - name: Native libraries list
      run: tree ${{ steps.vars.outputs.runtimes-dir }}
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
      
    - name: Build
      run: dotnet pack src/ggwave.net/ggwave.net.csproj -o nuget
      
    - name: Upload nuget packages artifact
      uses: actions/upload-artifact@v4
      with:
        name: nupkg
        path: nuget/*
    