name: Build .NET solution

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  call-build-submodule:
    uses: ./.github/workflows/build-submodule.yml

  build:
    needs: [ call-build-submodule ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current commit
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: false
      
    - name: Download native libraries
      uses: dawidd6/action-download-artifact@v9
      with:
        name: natives-*
        path: src/ggwave.net/runtimes/
        # put all artifact files in runtimes/
        merge_multiple: true
        branch: ${{ github.head_ref || github.ref_name }}
        workflow_search: true
        check_artifacts: true
        github_token:  ${{ secrets.GITHUB_TOKEN }}
        
    - name: Native libraries list
      run: tree src/ggwave.net/runtimes/
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
      
    - name: Restore dependencies
      run: dotnet restore src/ggwave.net/ggwave.net.sln
    - name: Build
      run: dotnet pack src/ggwave.net/ggwave.net.csproj -o nuget -c Release
      
    - name: Upload .net build artifacts
      # if: contains(github.ref, 'release') || github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: nupkg
        path: nuget/*
    
