# Build ggwave native submodule when it changes
name: build-submodule

on:
  workflow_dispatch:
  workflow_call:

jobs:
  check-existing-artifact:
    runs-on: ubuntu-latest
    outputs:
      artifact_exists: ${{ steps.check.outputs.exists }}

    steps:
      - name: Checkout current commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: false
      
      - name: Check for existing artifact
        id: check
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          ARTIFACTS=$(gh api repos/${{ github.repository }}/actions/artifacts?branch=${BRANCH_NAME}&filter=completed)
          EXISTS=true

          SUBMODULE_SHA=$(git submodule status ggwave | awk '{print $1}' | sed 's/[^0-9a-f]//g')
          ARTIFACT_NAME="natives-all-${SUBMODULE_SHA}"
          
          if echo "$ARTIFACTS" | jq -e ".artifacts[] | select(.name == \"$ARTIFACT_NAME\")" > /dev/null; then
            echo "artifact $ARTIFACT_NAME exists"
          else
            echo "artifact $ARTIFACT_NAME doesn't exist"
            EXISTS=false
          fi

          echo "RESULT: exists=$EXISTS"
          echo "exists=$EXISTS" >> $GITHUB_OUTPUT

  call-build-native:
    needs: [check-existing-artifact]
    if: needs.check-existing-artifact.outputs.artifact_exists == 'false'
    uses: ./.github/workflows/build-native.yml
