name: Trigger Build on Submodule Change

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  detect-submodule-change:
    runs-on: ubuntu-latest
    outputs:
      submodule_changed: ${{ steps.compare.outputs.changed }}

    steps:
      - name: Checkout current commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: false

      - name: Get previous commit hash
        id: prev
        run: echo "sha=$(git rev-parse HEAD^)" >> $GITHUB_OUTPUT

      - name: Save old submodule status
        run: |
          git checkout ${{ steps.prev.outputs.sha }}
          git submodule status ggwave > ../old.txt

      - name: Save new submodule status
        run: |
          git checkout ${{ github.sha }}
          git submodule update --init --recursive --depth 2
          git submodule status ggwave > ../new.txt

      - name: Compare submodule reference
        id: compare
        run: |
          if ! diff ../old.txt ../new.txt >/dev/null; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  check-existing-artifact:
    needs: detect-submodule-change
    runs-on: ubuntu-latest
    outputs:
      artifact_exists: ${{ steps.check.outputs.exists }}

    steps:
      - name: Check for existing artifact
        id: check
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git-submodule-sha=$(git submodule status ggwave | awk '{print $1}')
          ARTIFACTS=$(gh api repos/${{ github.repository }}/actions/artifacts)
          EXISTS=false
          for OS_NAME in Linux Windows; do
            ARTIFACT_NAME="natives-${git-submodule-sha}-${OS_NAME}"
            if echo "$ARTIFACTS" | jq -e ".artifacts[] | select(.name == \"$ARTIFACT_NAME\")" > /dev/null; then
              echo "exists=true" >> $GITHUB_OUTPUT
            fi
          done
          echo "exists=$EXISTS" >> $GITHUB_OUTPUT

  call-build-native:
    needs: [detect-submodule-change, check-existing-artifact]
    if: |
      needs.detect-submodule-change.outputs.submodule_changed == 'true' ||
      needs.check-existing-artifact.outputs.artifact_exists == 'false'
    uses: ./.github/workflows/build-native.yml
